#!/usr/bin/ksh -p

. /lib/svc/share/smf_include.sh

JAVA_BIN=/usr/bin/java

args=""

val=$(svcprop -p options/http_port $SMF_FMRI)
[ -n "$val" ] &&  args="$args --httpPort=$val"

val=$(svcprop -p options/httpListenAddress $SMF_FMRI)
[ -n "$val" ] &&  args="$args --httpListenAddress=$val"

val=$(svcprop -p options/prefix $SMF_FMRI)
[ -n "$val" ] &&  args="$args --prefix=$val"

echo $args

case "$1" in
'start')
        $JAVA_BIN -jar /export/home/jenkins/jenkins.war $args
        ;;

esac
exit $SMF_EXIT_OK
